In [100]:
import lxml
import pandas as pd
import requests
import re
from bs4 import BeautifulSoup

In [101]:
from fake_useragent import UserAgent                
ua = UserAgent()
headers = {'User-Agent': ua.random}

In [102]:
url = "https://www.transfermarkt.es/valencia-cf/kader/verein/1049/plus/0/galerie/0?saison_id=2022"

In [103]:
plantilla23_22 = requests.get(url, headers=headers)

In [104]:
plantilla23_22 = BeautifulSoup(plantilla23_22.text, "html.parser")

In [105]:
temp23={"Nombre":[],
        "Posicion":[],
        "Edad":[],
        "Nacionalidad":[],
        "Valor":[]
        }

SACAR EL VALOR DEL JUGADOR EN EL EQUIPO

In [106]:
for valor in plantilla23_22.find_all("td", class_ = "rechts hauptlink"):
    temp23["Valor"].append(valor.text)

In [107]:
temp23

{'Nombre': [],
 'Posicion': [],
 'Edad': [],
 'Nacionalidad': [],
 'Valor': ['25,00 mill. €',
  '1,00 mill. €',
  '500 mil €',
  '300 mil €',
  '200 mil €',
  '25 mil €',
  '6,00 mill. €',
  '5,00 mill. €',
  '3,50 mill. €',
  '2,50 mill. €',
  '1,00 mill. €',
  '200 mil €',
  '30,00 mill. €',
  '3,00 mill. €',
  '2,50 mill. €',
  '8,00 mill. €',
  '2,50 mill. €',
  '14,00 mill. €',
  '6,50 mill. €',
  '25,00 mill. €',
  '20,00 mill. €',
  '18,00 mill. €',
  '10,00 mill. €',
  '4,00 mill. €',
  '2,00 mill. €',
  '1,00 mill. €',
  '200 mil €',
  '100 mil €',
  '16,00 mill. €',
  '14,00 mill. €',
  '1,50 mill. €',
  '6,00 mill. €',
  '500 mil €',
  '2,40 mill. €',
  '7,00 mill. €',
  '4,00 mill. €',
  '3,00 mill. €',
  '2,50 mill. €',
  '800 mil €',
  '25 mil €']}

SACAR NOMBRE JUGADOR

In [108]:
nombres = plantilla23_22.find_all('img', class_='bilderrahmen-fixed lazy lazy')
for nombre in nombres:
    #jugador24 = nombre["title"]
    temp23["Nombre"].append(nombre["title"])

SACAR EDAD JUGADOR

Veo que desde la posicion 1 y cada 4 saco el TD donde esta la edad ya que ese campo no tiene ningún atributo o clase que pueda diferenciar del resto.
Saco la longitud total de el td para saber su longitud y recorrer cada campo de la edad.

In [109]:
edad = plantilla23_22.find_all("td",class_ = "zentriert")

longitud=(len(edad)-4) #Saco el total y en el range le pongo 97 porque es el último valor de la cadena que queremos sacar.

valores_edad = [edad[i].text.strip() for i in range(1, longitud, 4)]
temp23["Edad"]=valores_edad

SACAR LA POSICION
Como en el anterior no tenemos una etiqueta ni nada que nos indique el campo de la posicion tenemos que sacarlo
a traves de la posicion de la etiqueta.

In [110]:
posiciones = plantilla23_22.find_all("table",class_ = "inline-table")

longitud_pos = (len(posiciones))
for i in range(longitud_pos):
    #print(posiciones[i].find_all("td")[2].text.strip())
    temp23["Posicion"].append(posiciones[i].find_all("td")[2].text.strip())

SACAR NACIONALIDAD

saco el td con la clase, veo que los que tienen doble nacionalidad ocupan td diferentes por eso le decimos que coja todos los "img" y la primera posicion de cada td.

In [111]:
nacionalidades = plantilla23_22.find_all("td", class_='zentriert')
for nacion in nacionalidades:
    img = nacion.find_all("img", class_="flaggenrahmen")
    if img:
        #print(img[0].get("title"))
        temp23["Nacionalidad"].append(img[0].get("title"))

In [112]:
temp23

{'Nombre': ['Giorgi Mamardashvili',
  'Jaume Doménech',
  'Iago Herrerín',
  'Emilio Bernad',
  'Cristian Rivero',
  'Charlie Pérez',
  'Mouctar Diakhaby',
  'Cenk Özkacar',
  'Eray Cömert',
  'Gabriel Paulista',
  'Cristhian Mosquera',
  'Rubén Iranzo',
  'José Gayà',
  'Jesús Vázquez',
  'Toni Lato',
  'Thierry Correia',
  'Dimitri Foulquier',
  'Hugo Guillamón',
  'Uroš Račić',
  'Carlos Soler',
  'André Almeida',
  'Yunus Musah',
  'Nico González',
  'Ilaix Moriba',
  'Javi Guerra',
  'Koba Koindredi',
  'Tiago Ribeiro',
  'Yellu Santiago',
  'Samuel Lino',
  'Justin Kluivert',
  'Diego López',
  'Samu Castillejo',
  'Fran Pérez',
  'Manu Vallejo',
  'Maxi Gómez',
  'Hugo Duro',
  'Edinson Cavani',
  'Marcos André',
  'Alberto Marí',
  'Mario Dominguez'],
 'Posicion': ['Portero',
  'Portero',
  'Portero',
  'Portero',
  'Portero',
  'Portero',
  'Defensa central',
  'Defensa central',
  'Defensa central',
  'Defensa central',
  'Defensa central',
  'Defensa central',
  'Lateral izquierdo',
  'Lateral izquierdo',
  'Lateral izquierdo',
  'Lateral derecho',
  'Lateral derecho',
  'Pivote',
  'Pivote',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Mediocentro',
  'Extremo izquierdo',
  'Extremo izquierdo',
  'Extremo izquierdo',
  'Extremo derecho',
  'Extremo derecho',
  'Mediapunta',
  'Delantero centro',
  'Delantero centro',
  'Delantero centro',
  'Delantero centro',
  'Delantero centro',
  'Delantero centro'],
 'Edad': ['22',
  '32',
  '35',
  '23',
  '25',
  '21',
  '26',
  '22',
  '25',
  '32',
  '19',
  '20',
  '28',
  '20',
  '25',
  '24',
  '30',
  '23',
  '25',
  '26',
  '23',
  '20',
  '21',
  '20',
  '20',
  '21',
  '21',
  '19',
  '23',
  '24',
  '21',
  '28',
  '20',
  '26',
  '26',
  '23',
  '36',
  '26',
  '21',
  '19'],
 'Nacionalidad': ['Georgia',
  'España',
  'España',
  'España',
  'España',
  'España',
  'Guinea',
  'Turquía',
  'Suiza',
  'Brasil',
  'España',
  'España',
  'España',
  'España',
  'España',
  'Portugal',
  'Guadalupe',
  'España',
  'Serbia',
  'España',
  'Portugal',
  'Estados Unidos',
  'España',
  'Guinea',
  'España',
  'Francia',
  'Portugal',
  'España',
  'Brasil',
  'Países Bajos',
  'España',
  'España',
  'España',
  'España',
  'Uruguay',
  'España',
  'Uruguay',
  'Brasil',
  'España',
  'España'],
 'Valor': ['25,00 mill. €',
  '1,00 mill. €',
  '500 mil €',
  '300 mil €',
  '200 mil €',
  '25 mil €',
  '6,00 mill. €',
  '5,00 mill. €',
  '3,50 mill. €',
  '2,50 mill. €',
  '1,00 mill. €',
  '200 mil €',
  '30,00 mill. €',
  '3,00 mill. €',
  '2,50 mill. €',
  '8,00 mill. €',
  '2,50 mill. €',
  '14,00 mill. €',
  '6,50 mill. €',
  '25,00 mill. €',
  '20,00 mill. €',
  '18,00 mill. €',
  '10,00 mill. €',
  '4,00 mill. €',
  '2,00 mill. €',
  '1,00 mill. €',
  '200 mil €',
  '100 mil €',
  '16,00 mill. €',
  '14,00 mill. €',
  '1,50 mill. €',
  '6,00 mill. €',
  '500 mil €',
  '2,40 mill. €',
  '7,00 mill. €',
  '4,00 mill. €',
  '3,00 mill. €',
  '2,50 mill. €',
  '800 mil €',
  '25 mil €']}

In [113]:
temporada23_22 =  pd.DataFrame(temp23)

In [114]:
temporada23_22.head(10)

                 Nombre         Posicion Edad Nacionalidad          Valor
0  Giorgi Mamardashvili          Portero   22      Georgia  25,00 mill. €
1        Jaume Doménech          Portero   32       España   1,00 mill. €
2         Iago Herrerín          Portero   35       España      500 mil €
3         Emilio Bernad          Portero   23       España      300 mil €
4       Cristian Rivero          Portero   25       España      200 mil €
5         Charlie Pérez          Portero   21       España       25 mil €
6      Mouctar Diakhaby  Defensa central   26       Guinea   6,00 mill. €
7          Cenk Özkacar  Defensa central   22      Turquía   5,00 mill. €
8           Eray Cömert  Defensa central   25        Suiza   3,50 mill. €
9      Gabriel Paulista  Defensa central   32       Brasil   2,50 mill. €

In [115]:
temporada23_22.Edad = temporada23_22.Edad.astype(int)

In [116]:
temporada23_22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nombre        40 non-null     object
 1   Posicion      40 non-null     object
 2   Edad          40 non-null     int32
 3   Nacionalidad  40 non-null     object
 4   Valor         40 non-null     object
dtypes: int32(1), object(4)
memory usage: 1.5+ KB

In [117]:
temporada23_22.Valor = temporada23_22.Valor.str.replace("[^\d,.]", "", regex=True).str.replace(",", ".").str.extract(r'(\d+.\d+|\d+)').astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\raul_\AppData\Local\Temp\ipykernel_17332\334797184.py:1: SyntaxWarning: invalid escape sequence '\d'
  temporada23_22.Valor = temporada23_22.Valor.str.replace("[^\d,.]", "", regex=True).str.replace(",", ".").str.extract(r'(\d+.\d+|\d+)').astype(float)

Pasamos los valores a millones, sabemos que los valores altos que habian no corresponden al valor en millones ya que sabemos que 
la plantilla del valencia no tiene jugadores tan valiosos.

In [118]:
temporada23_22.loc[temporada23_22.Valor >= 100,"Valor"] = temporada23_22.loc[temporada23_22.Valor >= 100,"Valor"]/1000

In [119]:
temporada23_22["Valor millones"] = temporada23_22.Valor

In [120]:
temporada23_22 = temporada23_22.drop(columns=["Valor"])

In [121]:
temporada23_22

,Nombre,Posicion,Edad,Nacionalidad,Valor millones
0,Giorgi Mamardashvili,Portero,22,Georgia,25.0
1,Jaume Doménech,Portero,32,España,1.0
2,Iago Herrerín,Portero,35,España,0.5
3,Emilio Bernad,Portero,23,España,0.3
4,Cristian Rivero,Portero,25,España,0.2
5,Charlie Pérez,Portero,21,España,25.0
6,Mouctar Diakhaby,Defensa central,26,Guinea,6.0
7,Cenk Özkacar,Defensa central,22,Turquía,5.0
8,Eray Cömert,Defensa central,25,Suiza,3.5
9,Gabriel Paulista,Defensa central,32,Brasil,2.5
10,Cristhian Mosquera,Defensa central,19,España,1.0
11,Rubén Iranzo,Defensa central,20,España,0.2
12,José Gayà,Lateral izquierdo,28,España,30.0
13,Jesús Vázquez,Lateral izquierdo,20,España,3.0
14,Toni Lato,Lateral izquierdo,25,España,2.5
15,Thierry Correia,Lateral derecho,24,Portugal,8.0
16,Dimitri Foulquier,Lateral derecho,30,Guadalupe,2.5
17,Hugo Guillamón,Pivote,23,España,14.0
18,Uroš Račić,Pivote,25,Serbia,6.5
19,Carlos Soler,Mediocentro,26,España,25.0
20,André Almeida,Mediocentro,23,Portugal,20.0
21,Yunus Musah,Mediocentro,20,Estados Unidos,18.0
22,Nico González,Mediocentro,21,España,10.0
23,Ilaix Moriba,Mediocentro,20,Guinea,4.0
24,Javi Guerra,Mediocentro,20,España,2.0
25,Koba Koindredi,Mediocentro,21,Francia,1.0
26,Tiago Ribeiro,Mediocentro,21,Portugal,0.2
27,Yellu Santiago,Mediocentro,19,España,0.1
28,Samuel Lino,Extremo izquierdo,23,Brasil,16.0
29,Justin Kluivert,Extremo izquierdo,24,Países Bajos,14.0
30,Diego López,Extremo izquierdo,21,España,1.5
31,Samu Castillejo,Extremo derecho,28,España,6.0
32,Fran Pérez,Extremo derecho,20,España,0.5
33,Manu Vallejo,Mediapunta,26,España,2.4
34,Maxi Gómez,Delantero centro,26,Uruguay,7.0
35,Hugo Duro,Delantero centro,23,España,4.0
36,Edinson Cavani,Delantero centro,36,Uruguay,3.0
37,Marcos André,Delantero centro,26,Brasil,2.5
38,Alberto Marí,Delantero centro,21,España,0.8
39,Mario Dominguez,Delantero centro,19,España,25.0

In [122]:
temporada23_22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nombre          40 non-null     object
 1   Posicion        40 non-null     object
 2   Edad            40 non-null     int32
 3   Nacionalidad    40 non-null     object
 4   Valor millones  40 non-null     float64
dtypes: float64(1), int32(1), object(3)
memory usage: 1.5+ KB

In [123]:
ruta="D:\DATASCIENCE\Repositorios\ONLINE_DS_THEBRIDGE_RAULSOLER\Proyecto EDA\LIMGOHOME\DatasLimpios\Temporada23_22.csv"

temporada23_22.to_csv(ruta, index="False")

<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\raul_\AppData\Local\Temp\ipykernel_17332\2395487455.py:1: SyntaxWarning: invalid escape sequence '\D'
  ruta="D:\DATASCIENCE\Repositorios\ONLINE_DS_THEBRIDGE_RAULSOLER\Proyecto EDA\LIMGOHOME\DatasLimpios\Temporada23_22.csv"