In [2]:
import pandas as pd

In [7]:
df_ataque = pd.read_csv("./championsdata/attacking.csv")

In [9]:
df_ataque.head(20)

,serial,player_name,club,position,assists,corner_taken,offsides,dribbles,match_played
0,1,Bruno Fernandes,Man. United,Midfielder,7,10,2,7,7
1,2,Vinícius Júnior,Real Madrid,Forward,6,3,4,83,13
2,2,Sané,Bayern,Midfielder,6,3,3,32,10
3,4,Antony,Ajax,Forward,5,3,4,28,7
4,5,Alexander-Arnold,Liverpool,Defender,4,36,0,9,9
5,5,De Bruyne,Man. City,Midfielder,4,18,0,14,10
6,5,Modrić,Real Madrid,Midfielder,4,10,0,8,13
7,5,João Mário,Benfica,Midfielder,4,8,0,7,8
8,5,Mbappé,Paris,Forward,4,4,8,43,8
9,5,Gerard Moreno,Villarreal,Forward,4,0,3,9,7
10,5,Capoue,Villarreal,Midfielder,4,0,0,17,12
11,12,Parejo,Villarreal,Midfielder,3,36,0,4,12
12,12,Grimaldo,Benfica,Defender,3,11,1,10,10
13,12,Müller,Bayern,Forward,3,10,8,2,10
14,12,Arnold,Wolfsburg,Midfielder,3,10,0,1,6
15,12,Angeliño,Leipzig,Defender,3,8,0,4,5
16,12,Coman,Bayern,Forward,3,4,4,59,9
17,12,Bernardo Silva,Man. City,Midfielder,3,2,3,18,11
18,12,Bellingham,Dortmund,Midfielder,3,1,1,24,6
19,12,Zapata,Atalanta,Forward,3,0,7,10,6

In [10]:
df_int = pd.read_csv("./championsdata/attempts.csv")

In [12]:
df_int.head(10)

,serial,player_name,club,position,total_attempts,on_target,off_target,blocked,match_played
0,1,Benzema,Real Madrid,Forward,45,23,13,9,12
1,2,Salah,Liverpool,Forward,42,22,11,9,13
2,3,Mahrez,Man. City,Midfielder,37,18,8,11,12
3,4,Sané,Bayern,Midfielder,33,13,12,8,10
4,5,Lewandowski,Bayern,Forward,31,19,8,4,10
5,6,Luis Díaz,Porto,Forward,29,11,7,11,13
6,7,Martínez,Inter,Forward,28,7,10,11,8
7,8,Mbappé,Paris,Forward,27,16,6,5,8
8,8,Vinícius Júnior,Real Madrid,Forward,27,8,10,9,13
9,10,Havertz,Chelsea,Midfielder,26,11,9,6,9

In [13]:
df_def = pd.read_csv("./championsdata/defending.csv")

In [14]:
df_def.head(10)

,serial,player_name,club,position,balls_recoverd,tackles,t_won,t_lost,clearance_attempted,match_played
0,1,Casemiro,Real Madrid,Midfielder,76,31,13,18,19,11
1,1,Éder Militão,Real Madrid,Defender,76,19,6,13,32,12
2,1,Reinildo,Atlético,Defender,76,13,6,7,20,10
3,4,Fabinho,Liverpool,Midfielder,74,23,9,14,8,13
4,5,Albiol,Villarreal,Defender,73,9,6,3,62,12
5,6,Thiago Silva,Chelsea,Defender,65,9,4,5,17,9
6,7,Otamendi,Benfica,Defender,63,28,17,11,48,9
7,8,Capoue,Villarreal,Midfielder,62,11,1,10,29,12
8,8,Van Dijk,Liverpool,Defender,62,3,2,1,29,9
9,10,João Cancelo,Man. City,Defender,56,9,6,3,13,9

In [15]:
df_disci = pd.read_csv("./championsdata/disciplinary.csv")

In [53]:
df_disci.loc[df_disci.fouls_committed].groupby("club").value_counts()

club         serial  player_name   position    fouls_committed  fouls_suffered  red  yellow  minutes_played  match_played
Ajax         6       Haller        Forward     17               11              1    0       668             8               23
                     Álvarez       Midfielder  17               6               4    0       558             7               16
                     Gravenberch   Midfielder  17               11              1    0       703             8               13
Atlético     16      Reinildo      Defender    15               15              2    0       816             10               4
Barcelona    12      Gavi          Midfielder  16               7               2    0       398             6                6
Benfica      6       Otamendi      Defender    17               11              2    0       810             9               39
             12      Gilberto      Defender    16               13              1    0       715             9                9
Club Brugge  5       Balanta       Midfielder  18               3               4    0       407             5               63
Liverpool    12      Mané          Midfielder  16               19              2    0       822             13              15
             16      Keïta         Midfielder  15               7               0    0       487             10               6
Man. City    2       Rodri         Midfielder  19               4               2    0       842             10              74
Porto        12      Luis Díaz     Forward     16               10              1    0       908             13               5
Real Madrid  6       Casemiro      Midfielder  17               18              3    0       914             11              62
                     Éder Militão  Defender    17               16              4    0       1076            12              55
             16      Carvajal      Defender    15               6               3    0       959             11               1
Salzburg     2       Seiwald       Midfielder  19               3               2    0       649             8               91
             16      Capaldo       Midfielder  15               8               3    0       281             7                4
             20      Camara        Midfielder  14               23              2    0       672             8                3
Sheriff      20      Addo          Midfielder  14               4               3    0       491             6                1
Villarreal   2       Capoue        Midfielder  19               17              3    1       1046            12              94
Name: count, dtype: int64

In [44]:
df_disci.head(3)

,serial,player_name,club,position,fouls_committed,fouls_suffered,red,yellow,minutes_played,match_played
0,1,João Palhinha,Sporting CP,Midfielder,23,17,2,0,534,6
1,2,Capoue,Villarreal,Midfielder,19,17,3,1,1046,12
2,2,Rodri,Man. City,Midfielder,19,4,2,0,842,10

In [17]:
df_dis = pd.read_csv("./championsdata/distributon.csv")

In [29]:
df_dis.head(30)

,serial,player_name,club,position,pass_accuracy,pass_attempted,pass_completed,cross_accuracy,cross_attempted,cross_complted,freekicks_taken,match_played
0,1,Erokhin,Zenit,Midfielder,98.0,27,26,0,2,0,0,6
1,2,Eric García,Barcelona,Defender,97.5,203,197,0,0,0,1,4
2,3,Ulreich,Bayern,Goalkeeper,97.0,32,31,0,0,0,1,1
3,4,Rugani,Juventus,Defender,96.8,130,122,0,0,0,0,4
4,5,J. Timber,Ajax,Midfielder,95.8,497,474,0,1,0,14,8
5,6,Egan-Riley,Man. City,Defender,95.0,61,58,0,1,0,0,1
6,6,Mario Gaspar,Villarreal,Defender,95.0,32,29,0,1,0,1,2
7,8,Marlon,Shakhtar Donetsk,Defender,94.8,424,402,0,0,0,8,5
8,9,Süle,Bayern,Defender,94.7,429,413,0,2,0,9,7
9,9,Laporte,Man. City,Defender,94.7,707,672,0,0,0,10,9
10,11,Maycon,Shakhtar Donetsk,Midfielder,94.5,395,373,58,12,7,9,6
11,11,Nianzou,Bayern,Midfielder,94.5,199,192,0,0,0,5,4
12,13,Marcos Antônio,Shakhtar Donetsk,Midfielder,94.4,234,224,0,0,0,5,5
13,13,Stones,Man. City,Defender,94.4,545,523,0,1,0,8,8
14,15,Stepanenko,Shakhtar Donetsk,Midfielder,94.3,146,137,0,1,0,4,4
15,16,Rodri,Man. City,Midfielder,94.2,806,760,0,1,0,13,10
16,16,Matip,Liverpool,Defender,94.2,498,467,0,0,0,14,7
17,18,Martínez,Ajax,Defender,94.1,674,633,0,0,0,12,8
18,19,Arthur,Juventus,Midfielder,94.0,293,278,50,2,1,7,6
19,19,Bondar,Shakhtar Donetsk,Defender,94.0,105,99,0,0,0,3,1
20,19,Fábio Cardoso,Porto,Defender,94.0,39,36,0,0,0,2,2
21,19,Shabanov,Dynamo Kyiv,Defender,94.0,35,33,0,0,0,0,1
22,23,Paredes,Paris,Midfielder,93.8,315,298,0,0,0,10,5
23,24,Lindelöf,Man. United,Defender,93.6,280,263,50,2,1,8,5
24,24,Daniel Bragança,Sporting CP,Midfielder,93.6,66,61,0,0,0,2,5
25,24,Matheus Cunha,Atlético,Forward,93.6,19,17,0,0,0,0,5
26,27,Wijnaldum,Paris,Midfielder,93.4,97,89,0,0,0,3,5
27,27,Christensen,Chelsea,Defender,93.4,552,517,50,2,1,7,8
28,29,Kimpembe,Paris,Defender,93.3,376,352,0,0,0,15,7
29,29,Álvarez,Ajax,Midfielder,93.3,363,340,0,1,0,7,7

In [21]:
df_porte= pd.read_csv("./championsdata/goalkeeping.csv")

In [22]:
df_porte.head(10)

,serial,player_name,club,position,saved,conceded,saved_penalties,cleansheets,punches made,match_played
0,1,Courtois,Real Madrid,Goalkeeper,61,14,1,5,4,13
1,2,Rulli,Villarreal,Goalkeeper,41,16,0,3,12,12
2,3,Vlachodimos,Benfica,Goalkeeper,38,17,1,5,5,10
3,4,Athanasiadis,Sheriff,Goalkeeper,29,8,0,1,2,5
4,5,Mignolet,Club Brugge,Goalkeeper,28,20,0,0,1,6
5,6,Oblak,Atlético,Goalkeeper,26,10,0,3,2,10
6,7,Musso,Atalanta,Goalkeeper,21,13,0,1,1,6
7,8,Ersin Destanoğlu,Beşiktaş,Goalkeeper,20,17,0,0,0,5
8,9,De Gea,Man. United,Goalkeeper,19,9,0,1,0,7
9,9,Dahlin,Malmö,Goalkeeper,19,8,1,0,3,4

In [23]:
df_goles = pd.read_csv("./championsdata/goals.csv")

In [24]:
df_goles.head(10)

,serial,player_name,club,position,goals,right_foot,left_foot,headers,others,inside_area,outside_areas,penalties,match_played
0,1,Benzema,Real Madrid,Forward,15,11,1,3,0,13,2,3,12
1,2,Lewandowski,Bayern,Forward,13,8,3,1,1,13,0,3,10
2,3,Haller,Ajax,Forward,11,3,4,3,1,11,0,1,8
3,4,Salah,Liverpool,Forward,8,0,8,0,0,7,1,1,13
4,5,Nkunku,Leipzig,Midfielder,7,3,1,3,0,7,0,0,6
5,5,Mahrez,Man. City,Midfielder,7,1,4,2,0,7,0,2,12
6,7,Mbappé,Paris,Forward,6,6,0,0,0,6,0,0,8
7,7,Núñez,Benfica,Forward,6,5,0,1,0,6,0,1,10
8,7,Ronaldo,Man. United,Forward,6,5,0,1,0,4,2,0,7
9,7,Danjuma,Villarreal,Midfielder,6,3,3,0,0,6,0,1,11

In [40]:
df_goles.groupby("club")["goals"].sum().sort_values(ascending=False)

club
Bayern              30
Liverpool           30
Real Madrid         28
Man. City           28
Ajax                21
Chelsea             21
Villarreal          20
Paris               15
Leipzig             15
Sporting CP         14
Benfica             13
Atalanta            12
Man. United         12
Juventus            11
Salzburg            10
Dortmund            10
Zenit                9
Inter                9
Atlético             9
LOSC                 8
Sheriff              7
Young Boys           7
Milan                5
Club Brugge          5
Sevilla              5
Wolfsburg            5
Beşiktaş             3
Porto                2
Shakhtar Donetsk     2
Barcelona            2
Dynamo Kyiv          1
Malmö                1
Name: goals, dtype: int64

In [25]:
df_stats = pd.read_csv("./championsdata/key_stats.csv")

In [28]:
df_stats.head(100)

,player_name,club,position,minutes_played,match_played,goals,assists,distance_covered
0,Courtois,Real Madrid,Goalkeeper,1230,13,0,0,64.2
1,Vinícius Júnior,Real Madrid,Forward,1199,13,4,6,133.0
2,Benzema,Real Madrid,Forward,1106,12,15,1,121.5
3,Modrić,Real Madrid,Midfielder,1077,13,0,4,124.5
4,Éder Militão,Real Madrid,Defender,1076,12,0,0,110.4
...,...,...,...,...,...,...,...,...
95,Kimmich,Bayern,Midfielder,702,8,0,0,96.4
96,Marcos Llorente,Atlético,Midfielder,700,9,0,0,83.6
97,Azpilicueta,Chelsea,Defender,679,9,1,1,82
98,David,LOSC,Forward,679,8,3,0,86.1
99,Mbappé,Paris,Forward,673,8,6,4,65.2